export const IPC = {
  SESSION_CREATE: 'session:create',
  SESSION_RESUME: 'session:resume',
  SESSION_PROMPT: 'session:prompt',
  SESSION_CANCEL: 'session:cancel',
  SESSION_LIST: 'session:list',
  SESSION_SET_MODEL: 'session:set-model',
  SESSION_SET_THINKING: 'session:set-thinking',
  SESSION_SET_PERMISSION: 'session:set-permission',
  SYSTEM_DEFAULT_WORKDIR: 'system:default-workdir',
  SYSTEM_SELECT_WORKDIR: 'system:select-workdir',
  SYSTEM_SET_WORKDIR: 'system:set-workdir',
  CONFIG_GET: 'config:get',
  CONFIG_UPDATE_RUNTIME: 'config:update-runtime',
  AGENT_EVENT: 'agent:event',
  AGENT_APPROVAL: 'agent:approval',
  AGENT_APPROVAL_RESPOND: 'agent:approval:respond',
  AGENT_QUESTION: 'agent:question',
  AGENT_QUESTION_RESPOND: 'agent:question:respond',
  PREVIEW_SELECT_FILE: 'preview:select-file',
  PREVIEW_GIT_DIFF: 'preview:git-diff',
} as const;
