export const IPC = {
  SESSION_CREATE: 'session:create',
  SESSION_PROMPT: 'session:prompt',
  SESSION_CANCEL: 'session:cancel',
  SESSION_LIST: 'session:list',
  SESSION_SET_MODEL: 'session:set-model',
  SESSION_SET_THINKING: 'session:set-thinking',
  SESSION_SET_PERMISSION: 'session:set-permission',
  SYSTEM_DEFAULT_WORKDIR: 'system:default-workdir',
  CONFIG_GET: 'config:get',
  CONFIG_UPDATE_RUNTIME: 'config:update-runtime',
  AGENT_EVENT: 'agent:event',
  AGENT_APPROVAL: 'agent:approval',
  AGENT_APPROVAL_RESPOND: 'agent:approval:respond',
  AGENT_QUESTION: 'agent:question',
  AGENT_QUESTION_RESPOND: 'agent:question:respond',
} as const;
